### ISSUE TITLE
Significance of update_scales() during training

### ISSUE THREAD

**Issue by mmaaz60** [apple/ml-cvnets#14]
Hi, Thank you for the great work.

I have a question related to the `update_scales()` function in `VariableBatchSamplerDDP` class. I see by default the code is not updating scales during training as `self.scale_inc=False`. As the code is there I am assuming that you could have tried enabling it. If so, may you provide the ablation results that you got with and without using `update_scales()` during training? Thank you

**Comment by sacmehta** [comment]
You can use it to dynamically scale the input resolution during the training. We studied it briefly and found that it helps in improving training efficiency. However, careful selection of scales is required in order to get good accuracy with this setting.
