### ISSUE TITLE
Inference Time comparision between Resnet and MobileViT

### ISSUE THREAD

**Issue by daebakk** [apple/ml-cvnets#22]
Hello!

I'm Dae Hyun Kim, Korean student

I want to know the Inference time(or FPS) of Resnet and Mobile ViT on ImageNet-1k validation set

Are there real results about it?

I ran the evaluation code(main_eval.py) myself using a single GeForce RTX 2080 TI GPU.

The results are as follows.

**Mobile Vit XS**

![스크린샷, 2022-06-04 20-57-01](https://user-images.githubusercontent.com/41338783/171997984-f9fd3f5f-dbfe-4c8b-a9ba-683aa8132832.png)

**Mobile Vit S**

![스크린샷, 2022-06-04 20-45-39](https://user-images.githubusercontent.com/41338783/171998008-8f6175fc-4ff3-495a-aeb8-1a93d5d2cb2d.png)

**Resnet50**

![스크린샷, 2022-06-04 21-04-13](https://user-images.githubusercontent.com/41338783/171998176-93c2be57-1f5c-4b45-a19d-7301ed68487a.png)

I know these are not inference time but evaluation time. However, based on this data, it can be estimated that mobilevit is slower than Resnet when measured by GPU, is this speculation true?

**Comment by sacmehta** [comment]
On GPUs, this speculation is true. Similar observations are made in prior works about ViTs and CNNs (e.g., see [ResNet strikes back paper](https://arxiv.org/abs/2110.00476)) as well as our work on [efficient self-attention](https://arxiv.org/abs/2206.02680).

**Comment by daebakk** [comment]
Thank you for your efforts :)
