### ISSUE TITLE
[GitHub Pages] Missing link on "Installation" page

### ISSUE THREAD

**Issue by UPstartDeveloper** [apple/ml-cvnets#23]
Hello,

It seems like the [source for the "Installation" page](https://github.com/apple/ml-cvnets/blob/main/docs/source/installation.rst) meant to include a link to an external page for help on setting up a `conda` environment. Could you please share which website you maybe had in mind?

I think the ["Get Started" page](https://pytorch.org/get-started/locally/) on the PyTorch docs might be a good option. Could open up a PR to make this fix.

Thank you for this great work!

**Comment by farzadab** [comment]
Hi!

Thanks for pointing that out. Fixed.
This was simply a link to Conda's documentation: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

But feel free to open up a PR if you believe more detailed instructions are required.

Cheers!
