### ISSUE TITLE
add the new MobileOne model

### ISSUE THREAD

**Issue by rotem154154** [apple/ml-cvnets#24]
Thanks apple for open sourcing sota deep learning models to us!
I seen that you added recently the brand new mobileViTv2.
it could be nice to see also an option to downlad the new MobileOne model by apple: https://arxiv.org/abs/2206.04040v1

thanks!

**Comment by JacopoMangiavacchi** [comment]
Meta has an implementation for MobileOne in mobile-vision 
https://github.com/facebookresearch/mobile-vision/pull/91/files#diff-0b527c9b0026d923d70c931b8871fc497e32ae9ed87ca503ca10d849ac9108d1
