### ISSUE TITLE
MobileViT use a larger GPU memory than AlexNet?

### ISSUE THREAD

**Issue by anthonyweidai** [apple/ml-cvnets#3]
Is it normal? I noticed that mobilevit have no more than 10 M parameters.

**Comment by sacmehta** [comment]
This is expected because architectures are different. MobileViT (and other transformer-based models) involve operations (e.g., dot-product attention) that do not involve any learnable parameters, but requires GPU memory to save activations that could be used for forward/backward propagation.

**Comment by anthonyweidai** [comment]
I learnt from that during these days. Thanks for your further explanation!
