### ISSUE TITLE
Integrate MobileViTv2 with retinanet for object detection

### ISSUE THREAD

**Issue by Jmei1994** [apple/ml-cvnets#33]
Hi, I have notice that you integrated MobileViTv2 with SSDLite for object detection. I'm wondering if it is also an option to  integrate MobileViTv2 with retinanet for object detection? I'm asking because retinanet seems achieve better performance than SSDLite. Thanks

**Comment by sacmehta** [comment]
Hi, We welcome pull requests for different object detectors.

**Comment by Jmei1994** [comment]
Hi Sacmehta. Why did you integrate MobileViTv2 with SSDLite instead of retinanet for object detection experiment in paper?

**Comment by sacmehta** [comment]
We follow MobileNets for object detection setup and they use SSDLite. For a fair comparison with these competing methods, we use SSDLite.
