### ISSUE TITLE
Q: Video MobileViTv2 Kinetics-400

### ISSUE THREAD

**Issue by pornosaur** [apple/ml-cvnets#37]
Hi there, thank you for sharing your work! Very clean code, and easy to understand :]

Have you trained a video model based on MobileVitV2 on Kinetics-400 yet?
If so, are you going to share the weights? 

Thank you.

**Comment by sacmehta** [comment]
Hi @pornosaur , we did not train MobileViTv2 on the Kinetics dataset.
