### ISSUE TITLE
Running Training for Segmentation ScanNet

### ISSUE THREAD

**Issue by nbansal90** [apple/ml-cvnets#38]
Hello @sacmehta,

Thank you for setting up this exhaustive repository!

I was looking to run the semantic segmentation `training` for the ScanNet dataset (for 10 selected classes.) I have gone ahead and made the following changes specific for the ScanNet dataset:

- Complete Dataloader pipeline, as suggested in [README](https://github.com/apple/ml-cvnets/blob/main/docs/source/en/general/README-new-dataset.md)
- Config Files
- Saving provided `MobileNetv2` & `MobileNetVit` model trained on **ADE20K**, `MobileNetv2` & `MobileNetVit` model trained on **ImageNet** on [README](https://github.com/apple/ml-cvnets/blob/main/docs/source/en/general/README-model-zoo.md).

**Query**:
I want to use the pre-trained model weights (of the ADE20K dataset), to start the training for ScanNet Dataset. You have pointed out to use this [apple resource](https://apple.github.io/ml-cvnets/en/models/segmentation/README-segmentation-deeplabv3-tutorial.html#training-segmentation-network) to train the Deeplabv3 model. I have gone ahead and created a script file for it, with the following content:
`export CONFIG_FILE="./config/segmentation/scannet/deeplabv3_mobilevitv2-0.5.yaml"`
`export IMAGENET_PRETRAINED_WTS="./model_weights/mobilevitv2-0.5.pt"`
`PYTHONWARNINGS="ignore" cvnets-train --common.config-file $CONFIG_FILE --common.results-loc deeplabv3_results --model.classification.pretrained $IMAGENET_PRETRAINED_WTS`.

- When I run the above script on my terminal, I get the following error:
`set_env_segmentation.sh: 3: cvnets-train: not found`

- I was wondering if you could provide me with the sequence of commands, which must be executed on the terminal, to get the training model running on a GPU, which uses a pre-trained model, trained on Imagenet and ADE20K.

Thank you again for the resource!

Nitin Bansal

**Comment by sacmehta** [comment]
Looks like you did not install CVNets. Run below command from CVNets root to install it. Hope this helps.

`pip install —editable .`
