### ISSUE TITLE
Question about video_reader

### ISSUE THREAD

**Issue by andrewwang0612** [apple/ml-cvnets#39]
Thanks for such a great job!
I want to ask questions about the custom dataset and
the parameters in this directory:config/video_classification/kinetics/mobilevit_st.yaml
![image](https://user-images.githubusercontent.com/87011223/179888258-ba784f93-7969-46dd-9103-da5a2ff279ac.png)
In this file,clips_per_video and num_frames_per_clip are 8,
Assume for 2 videos with 8 and 64 frames,
The dataset size will be (1+8)?

Another questoin:
If the length of the video longer than 64 frames,
Do I have to seperate the video to shorter segment or I can just modeify the parameter '' clips_per_video''?

Thank you for your help!!!

**Comment by sacmehta** [comment]
First of all, you are using the hyper-parameters for `video_variable_seq_sampler `, but using `video_batch_sampler`.

The `video_variable_seq_sampler` divides a video into `K` clips. The value of `K` is randomly sampled between 1 (specified using `min_clips_per_video`) and 8 (specified using `max_clips_per_video`) at every training iteration. Within each clip, we now select `8` frames randomly (specified using `num_frames_per_clip`).

If the video is shorter, then we do sampling with repetition. If it is longer than desired length, then we randomly select frames. You can see more details about the sampling logic [here](https://github.com/apple/ml-cvnets/blob/84d992f413e52c0468f86d23196efd9dad885e6f/data/video_reader/base_video_reader.py#L136).

Hope this helps!

**Comment by andrewwang0612** [comment]
OK,I see.
Thank you for your help!!!
