### ISSUE TITLE
How do I use multiple nodes and multiple gpus to train？

### ISSUE THREAD

**Issue by CocaIceCola7759** [apple/ml-cvnets#4]
How do I use multiple nodes and multiple gpus to train？

**Comment by sacmehta** [comment]
Right now, the codebase supports single node multiple GPU training. We will be adding support to multi-node multi-GPU in future versions.

**Comment by sacmehta** [comment]
CVNets-v0.2 supports multi-node training. An example of training a classification model is given [here](https://github.com/apple/ml-cvnets/blob/main/docs/source/en/models/classification/README-classification-tutorial.md#training-on-the-imagenet-dataset).
