### ISSUE TITLE
Code Unfriendly for Downstream Tasks

### ISSUE THREAD

**Issue by YimingMa** [apple/ml-cvnets#42]
Hi @sacmehta,

First I'd like to thank you for your contribution of MobileViTs. But I have the code in this repo very unfriendly for downstream tasks. I cannot find which snippets are related to MobileViTs as well as their detailed configurations. Although other have been some other GitHub repos providing unofficial code for MobileViT-V1, but the I couldn't load pre-trained weights from this one. Could you please re-organise your code here to make it more useful for the community?

Many thanks,
Yiming

**Comment by farzadab** [comment]
Hi Yiming,

Thanks for the comment. Can you elaborate on what changes you think are required and what downstream tasks you've had trouble with extending the backbone to?

Snippets for MobileViT are clearly separated from other models:
- MobileViT-V1 Configs [config/mobilevit.py](https://github.com/apple/ml-cvnets/blob/main/cvnets/models/classification/config/mobilevit.py)
- MobileViT-V1 Block: [mobilevit_block.py](https://github.com/apple/ml-cvnets/blob/main/cvnets/modules/mobilevit_block.py)
- MobileViT-V1 Model: [mobilevit.py](https://github.com/apple/ml-cvnets/blob/main/cvnets/models/classification/mobilevit.py)
  - The model extends our base classifier class: [base_cls.py](https://github.com/apple/ml-cvnets/blob/main/cvnets/models/classification/base_cls.py)

Cheers,
Farzad

**Comment by YimingMa** [comment]
Hi Farzad,

Thank you for your reply.
I'd like to leverage these lightweight transformers and their pre-trained weights on downstream tasks such as crowd counting. However, I find the code in this repo highly integrated, and I can't find a simple way to define the model. (I guess this repo is mainly designed for reproducing the results.) So, is it possible that you add some functions that will directly return the model (preferably with options to load weights)? I have tried myself [here](https://github.com/YimingMa/MobileViT), but I'm not very sure whether everything is correct.

Many thanks,
Yiming

**Comment by sacmehta** [comment]
If you are only interested in pre-trained weights, then you can also port it from timm library.

https://github.com/rwightman/pytorch-image-models

**Comment by YimingMa** [comment]
Hi Sachin,

I am interested in the pre-trained weights of the backbone (so not the final prediction layer), and thanks for the recommendation. That repo is indeed very handy.

Many thanks,
Yiming

**Comment by cszhbo** [comment]
> If you are only interested in pre-trained weights, then you can also port it from timm library.
> 
> https://github.com/rwightman/pytorch-image-models

Are the weights in timm from Apple's official training?

**Comment by sacmehta** [comment]
Yes, pretrained weights in timm library are from this repository.

**Comment by cszhbo** [comment]
> 

OK. Thanks for your reply.
