### ISSUE TITLE
Using mobilevit attention layers to create heat map

### ISSUE THREAD

**Issue by zas97** [apple/ml-cvnets#44]
Is it possible to use the attention layers of the mobilevit model to create a heatmap on the image input with the parts of the image used? I'm looking to something like this : 
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/7695785/184843143-47bc3ad6-ab2d-40a1-b08b-343c6359b936.png">

**Comment by sacmehta** [comment]
Hi @zas97 ,

This is definitely possible and you need to write the code for the same. We do not support it. 

In our MobileViTv2 paper, we did [visualize the context maps](https://github.com/apple/ml-cvnets/blob/84d992f413e52c0468f86d23196efd9dad885e6f/cvnets/layers/linear_attention.py#L82) and you may use it as a reference for implementing for multi-headed attention in transformers.

**Comment by arunsubk** [comment]
Hi @zas97 , Could you please let me know if you were able to find or create such code as suggested by @sacmehta ? If yes some pointers could really help. I am unable to wrap my head around how I can get an attention heat map from a final attention map for MobileVit of shape 1,4,4,16,16 i.e. batch_size, nbr of heads, dimension, attention score, attention score for input image dimension of 256,256,3 can be remapped to attention image.

**Comment by zas97** [comment]
Not really I left the project
