### ISSUE TITLE
How to build the MobileViT model?

### ISSUE THREAD

**Issue by sayannath** [apple/ml-cvnets#46]
Following the steps given in the `README.md` but unable to build the model. 

If I am running the script `mobilevit.py`. It is showing a relative import error.

```bash
ModuleNotFoundError: No module named 'utils'
```

Any solution? @sacmehta

**Comment by sacmehta** [comment]
@sayannath It appears that you are not building from root folder of this codebase. The easiest would be to adapt [test_model.py](https://github.com/apple/ml-cvnets/blob/84d992f413e52c0468f86d23196efd9dad885e6f/tests/test_model.py#L20) file. I hope this helps.

**Comment by sacmehta** [comment]
It seems that your issue is resolved, so closing it. Feel free to reopen if it is not resolved.

**Comment by prsbsvrn** [comment]
Hello,

I am running the command you provided: "python test_model.py --common.config-file ../config/classification/imagenet/mobilevit.yaml". However, I encountered the following error:

Traceback (most recent call last):
  File "/home/../test/ml-cvnets/tests/test_model.py", line 19, in <module>
    from tests.configs import get_config
  File "/home/../test/ml-cvnets/tests/../tests/configs.py", line 8, in <module>
    from options.opts import get_training_arguments
  File "/home/../test/ml-cvnets/options/opts.py", line 11, in <module>
    from data.collate_fns import arguments_collate_fn
ImportError: cannot import name 'arguments_collate_fn' from 'data.collate_fns' (unknown location)


Additionally, could you provide code to plot the top1 and top5 accuracies, as well as the loss per epoch?
