### ISSUE TITLE
FLOPs calculation different from paper?

### ISSUE THREAD

**Issue by StephenEkaputra** [apple/ml-cvnets#47]
Hi, I trained your code using MobileViT-XS model.
The flops don't seem same to the paper.
For example, the paper mentions that the flops are 0.7G, but with your code, the flops are 0.9G.
Specifically, flops = 986.269M. 
Thank you.

**Comment by sacmehta** [comment]
Hi,

as mentioned in Table 10 caption of the paper, FLOPs are measured or an input of 224x224. Are you using 224x224 as a resolution for measuring FLOPs?

**Comment by StephenEkaputra** [comment]
Hi,
Thank you for your reply.
I have some questions again.
Is 224x224 resolution only used for params. and flops measurement in the paper?
But, the accuracy follows 256x256 resolution?

**Comment by sacmehta** [comment]
That is correct. FLOPs are measured at 224x224 and inference time is measured at 256x256.

note that network parameters are independent of input resolution.
