### ISSUE TITLE
Dose batch sampler make model learns same weight in every training repeatation?

### ISSUE THREAD

**Issue by YHYeooooong** [apple/ml-cvnets#49]
Hi! Thanks for sharing great work!

I have a question about the sampler

I am working on some training examples with variable_batch_sampler and batch sampler.
I'm trying to get average ACC over 5 times training (repeat training 5 times in the same setting)
Best validation ACCs may be similar (not the same) in every repeated trained model with both samplers. 
But when I used the batch sampler, the all best val ACC of the repeated model are the same. Is that right?

I'm working with this yaml file

[0707_mobilevits_real_defualt_lr0.0001_cosine_advanced_multiscale.docx](https://github.com/apple/ml-cvnets/files/9554365/0707_mobilevits_real_defualt_lr0.0001_cosine_advanced_multiscale.docx)

with this shell script command

```
for iter in '1' '2' '3' '4' '5'
do


    CUDA_VISIBLE_DEVICES=3 cvnets-train --common.config-file ./config/classification/CBIS-DDSM_2c_womulti/0707_mobilevits_real_defualt_lr0.0001_cosine_advanced_multiscale.yaml --common.results-loc ./results/2class_iters_wo_multi/iter$iter --model.classification.finetune-pretrained-model --model.classification.n-pretrained-classes 1000 --model.classification.pretrained ./weights/mobilevit_s.pt
done
```

and when I repeated training 5 times, best val ACC (same value 72.5467) appear in 268 epoch.
[comparing_iterations.xlsx](https://github.com/apple/ml-cvnets/files/9554553/comparing_iterations.xlsx)

This result is right?

Also I modified some code because to tracking the training information.

modified code is under hear

[code.zip](https://github.com/apple/ml-cvnets/files/9554591/code.zip)

**Comment by sacmehta** [comment]
Hi, if you are looking to measure run-to-run variation, then you should change the ransom seed. Right now, you are using a default seed of 0.

**Comment by sacmehta** [comment]
You only need to add random seed in config file. No change in code.

It depends on several factors, including dataset size, optimization updates, run to run variance etc. 

Try to train batch and multi-scale sampler for the same number of iterations and see if you observe any performance gains.

**Comment by YHYeooooong** [comment]
Thank you for your kind response! 
I will change the seed value!
