### ISSUE TITLE
No tutorial for inference

### ISSUE THREAD

**Issue by iantimmis** [apple/ml-cvnets#51]
Appears to be no instructions for running inference with a model in python

**Comment by sacmehta** [comment]
We do provide examples for inference. Please check the documentation.

1. [Segmentation inference example](https://apple.github.io/ml-cvnets/en/models/segmentation/README-segmentation-deeplabv3-tutorial.html#qualitative-evaluation)
2. [Detection inference example](https://apple.github.io/ml-cvnets/en/models/detection/README-detection-SSD-tutorial.html#qualitative-evaluation)
3. [Classification inference example](https://apple.github.io/ml-cvnets/en/models/classification/README-classification-tutorial.html#evaluating-the-classification-model)
