### ISSUE TITLE
MobileViT (version 1) pre-training dataset

### ISSUE THREAD

**Issue by YHYeooooong** [apple/ml-cvnets#56]
Hello! thanks for sharing the great work!

I have a small question about the pre-training dataset. 
Did all MobileViT (version 1)  models pre-trained on ImageNet-1k? 
I guess they did, but I  want to make sure.
Thanks!

![mobilevit](https://user-images.githubusercontent.com/43724177/196030690-4c93ee06-fe61-4ba1-b461-80256d5c5495.png)

**Comment by sayannath** [comment]
Yes they are pre-trained weights of the ImageNet-1k dataset.

**Comment by YHYeooooong** [comment]
Thanks!

**Comment by JUNSUNGKIM99** [comment]
Hello! Thanks for your effort!

I also have a question about dataset.
In my situation, i'm going to test the cvnets briefly. 
There was a problem setting the dataset in the config file. Do I actually have to download imagenet 1k dataset?

Thanks!

**Comment by farzadab** [comment]
Yes, you’ll have to download the dataset and then set train_root and
val_root to point to where the dataset is located.
