### ISSUE TITLE
module 'torchvision.transforms' has no attribute 'RandAugment'

### ISSUE THREAD

**Issue by liamsun2019** [apple/ml-cvnets#61]
Hi author,

When I train with command line:
PYTHONWARNINGS="ignore" cvnets-train --common.config-file config/detection/ssd_coco/mobilevit_v2.yaml --common.results-loc ssdlite_mobilevitv2_results/width_0_5_0 --common.override-kwargs model.classification.mitv2.width_multiplier=0.5

following error message rises up:
 class RandAugment(BaseTransformation, T.RandAugment):
AttributeError: module 'torchvision.transforms' has no attribute 'RandAugment'

My environment:
torch==1.9.0+cu111
torchvision==0.10.0+cu111
 Suppose meet the requirement. Any suggestions? Thanks.

**Comment by sacmehta** [comment]
RandAugment is added in recent versions of torchvision. You may want to try torch>=0.11

**Comment by liamsun2019** [comment]
You are right. I upgraded to torchvision==0.11.2 and it goes well. Thanks.
