### ISSUE TITLE
train_2017.txt in coco_preprocess

### ISSUE THREAD

**Issue by siangyang** [apple/ml-cvnets#70]
Hi,
When I trying to train pascal VOC on semantic seg task,
I am faced with missing of train_2017.txt.

Is there any instruction to generate train_2017.txt for COCO dataset?

Thanks!

**Comment by sacmehta** [comment]
Hi,

sorry for the missing documentation. We followed [EdgeNets](https://github.com/sacmehta/EdgeNets/blob/2b232d3f7fb60658755dad1ebca0ffc895cc795e/data_loader/segmentation/coco.py#L89) for processing COCO data in PASCAL VOC format. Hope this helps!

**Comment by siangyang** [comment]
It works! Thanks for the fast reply.
