### ISSUE TITLE
bug in coco_ssd.py

### ISSUE THREAD

**Issue by MLRadfys** [apple/ml-cvnets#76]
Hi,

I noticed a small mistake in the coco_ssd.py script.

In def __getitem__(...):

`
        boxes, labels = self.get_boxes_and_labels(
            image_id=image_id, image_width=im_width, image_height=im_height
        )`

self.get_boxes_and_labels() returns boxes, labels and masks (or None) and should be changed to:

`
        boxes, labels, _ = self.get_boxes_and_labels(
            image_id=image_id, image_width=im_width, image_height=im_height
        )`

Cheers,

M

**Comment by darwinharianto** [comment]
https://github.com/apple/ml-cvnets/blob/c668ad13d67b3e8829e810d4b6e16ad7f77fd4aa/data/datasets/detection/coco_ssd.py#L158

it looks correct

**Comment by mchorton** [comment]
Marking resolved per @darwinharianto’s comment
