### ISSUE TITLE
Question: Do you have removed the support for video classification?

### ISSUE THREAD

**Issue by MasterHM-ml** [apple/ml-cvnets#89]
I am trying to fine-tune mobile vit for video classification, but I couldn't find any guide, docs and configs for video data and model handling in the latest repo. However, this kind of stuff is available in older versions. I am mentioning [one](https://github.com/apple/ml-cvnets/tree/84d992f413e52c0468f86d23196efd9dad885e6f) of those versions here for reference. 

Do you have removed the support for video classification? How I can fine-tune a pre-trained model for video classification using this awesome repository?

**Comment by Tranbaber** [comment]
@MasterHM-ml 
Hello! I'm trying to train MobileViT model, but I'm having the following problem and am asking for help

File "C:\Users\72344.conda\envs\MobileViTv2\Scripts\cvnets-train.exe_main_.py", line 4, in ModuleNotFoundError: No module named 'main_train'

And I tried to download this module, but show
"ERROR: Could not find a version that satisfies the requirement main_train (from versions: none)
ERROR: No matching distribution found for main_train"

Can you tell what can I do? Thank you very much!

**Comment by mchorton** [comment]
Hi @MasterHM-ml ,

There were a few pipeline changes to video loaders in the newest release, that did not maintain backwards compatibility with our mobilevit video training recipes. We decided to remove some of the video models during the new release as a result, to avoid creating reproducibility issues. Please use the older version for mobile vit training. Sorry for the inconvenience.
