### ISSUE TITLE
ModuleNotFoundError: No module named 'main_train'

### ISSUE THREAD

**Issue by prsbsvrn** [apple/ml-cvnets#94]
Hi
I follow the installation part but I got this error "ModuleNotFoundError: No module named 'main_train'". I don't know how can I solve it. I would appreciate if someone answers my issue. 
This is contents of my cvnets-train:
```
import re
import sys
from main_train import main_worker
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main_worker())
```

**Comment by Sina-Najafi** [comment]
Hi there! I hope you are doing ok.
here is my solution:
Write py_modules=["main_train", "main_eval", "main_conversion", "main_loss_landscape"],
 in setup.py before entry_points as an argument in the setup() function. and then run pip install --editable . to reinstall the package with these changes.
 Good Luck

**Comment by prsbsvrn** [comment]
> Hi there! I hope you are doing ok. here is my solution: Write py_modules=["main_train", "main_eval", "main_conversion", "main_loss_landscape"], in setup.py before entry_points as an argument in the setup() function. and then run pip install --editable . to reinstall the package with these changes. Good Luck

Thank you
